version: "3"

services:
  tests:
    container_name: tests
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - test.env
    volumes:
      - ./:/app
    command: >
      sh -c "python3.11 manage.py migrate &&
             python3.11 manage.py test"
    networks:
      - django-network

networks:
  django-network:
    driver: bridge