version: "3"

services:
  django:
    container_name: dev-django
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    command: >
      sh -c "python3.11 manage.py migrate &&
             python3.11 manage.py runserver 0.0.0.0:8000"
    env_file:
      - dev.env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - django-network

  db:
    container_name: dev-db
    image: postgres:alpine
    volumes:
      - ./dev-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - django-network

  cache:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./cache:/data
    ports:
    - "6379:6379"
    networks:
      - django-network

networks:
  django-network:
    driver: bridge
