# Generated by Django 4.2.3 on 2023-08-16 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
