# Generated by Django 4.2.3 on 2023-08-17 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
    ]
